/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.Observable;
import java.util.Observer;

import controller.KeyNewAttributeController;
import controller.okButtonNewAttributeController;
import model.ProjectUML;

/**
 *
 * @author digeona
 */
public class NewAttributeView extends javax.swing.JFrame implements Observer{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProjectUML model;
	private int index;

	/**
	 * Creates new form NewAttributeView
	 */
	public NewAttributeView(ProjectUML model,int i) {
		this.model=model;
		model.addObserver(this);
		this.index=i;
		initComponents();
		this.setLocation(100, 100);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		visibilityComboBox = new javax.swing.JComboBox<String>();
		typeComboBox = new javax.swing.JComboBox<String>();
		nameTextField = new javax.swing.JTextField();
		visibilityLabel = new javax.swing.JLabel();
		typeLabel = new javax.swing.JLabel();
		nameLabel = new javax.swing.JLabel();
		cancelButton = new javax.swing.JButton();
		okButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();


		//setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("New Attribute");

		visibilityComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "private", "protected", "default", "public" }));
		visibilityComboBox.setSelectedIndex(2);

		//typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		typeComboBox.setModel(new ComboBoxTypeModel(model,0));
		typeComboBox.setSelectedIndex(0);

		visibilityLabel.setText("Visibility");

        nameTextField.addKeyListener(new KeyNewAttributeController(this,model));

		
		typeLabel.setText("Type");

		nameLabel.setText("Name");

		cancelButton.setText("Cancel");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dispose();
			}
		});

		okButton.setText("OK");
		okButton.addActionListener(new okButtonNewAttributeController(this));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(visibilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
						.addContainerGap())
						.addGroup(layout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addComponent(visibilityLabel)
								.addGap(41, 41, 41)
								.addComponent(typeLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(nameLabel)
								.addGap(92, 92, 92))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(cancelButton)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(okButton)
										.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addContainerGap()
												.addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(14, 14, 14)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(visibilityLabel)
								.addComponent(typeLabel)
								.addComponent(nameLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(visibilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(warningLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(okButton)
												.addComponent(cancelButton)))
				);

		pack();
	}// </editor-fold>                        

	public javax.swing.JButton getOkButton() {
		return okButton;
	}                                       

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewAttributeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewAttributeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewAttributeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewAttributeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewAttributeView(new ProjectUML(),0).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JButton okButton;
	private javax.swing.JComboBox<String> typeComboBox;
	private javax.swing.JLabel typeLabel;
	private javax.swing.JComboBox<String> visibilityComboBox;
	private javax.swing.JLabel visibilityLabel;
    private javax.swing.JLabel warningLabel;
	// End of variables declaration//GEN-END:variables

	public javax.swing.JTextField getNameTextField() {
		return nameTextField;
	}

	public javax.swing.JComboBox<String> getTypeComboBox() {
		return typeComboBox;
	}

	public javax.swing.JComboBox<String> getVisibilityComboBox() {
		return visibilityComboBox;
	}

	public ProjectUML getModel() {
		return model;
	}

	public int getIndex() {
		return index;
	}

	@Override
	public void update(Observable o, Object arg) {
		warningLabel.setText(model.getWarning());
	}



}

